export const GDSA = {};

GDSA.attributes = {
    none: "",
    MU: "MU",
    KL: "KL",
    IN: "IN",
    CH: "CH",
    FF: "FF",
    GE: "GE",
    KO: "KO",
    KK: "KK"
}

GDSA.meleeSkills = {
    none: "",
    bastardsword: "GDSA.meleeskill.bastardsword",
    dagger: "GDSA.meleeskill.dagger",
    rapier: "GDSA.meleeskill.rapier",
    club: "GDSA.meleeskill.club",
    halberd: "GDSA.meleeskill.halberd",
    chainstaff: "GDSA.meleeskill.chainstaff",
    chainweapon: "GDSA.meleeskill.chainweapon",
    lance: "GDSA.meleeskill.lance",
    whip: "GDSA.meleeskill.whip",
    brawl: "GDSA.meleeskill.brawl",
    wrestle: "GDSA.meleeskill.wrestle",
    saber: "GDSA.meleeskill.saber",
    sword: "GDSA.meleeskill.sword",
    spear: "GDSA.meleeskill.spear",
    staff: "GDSA.meleeskill.staff",
    twohandflail: "GDSA.meleeskill.twohandflail",
    twohandclub: "GDSA.meleeskill.twohandclub",
    twohandsword: "GDSA.meleeskill.twohandsword"
}

GDSA.rangeSkills = {
    none: "",
    crossbow: "GDSA.rangeskill.crossbow",
    siegeweapon: "GDSA.rangeskill.siegeweapon",
    blowgun: "GDSA.rangeskill.blowgun",
    bow: "GDSA.rangeskill.bow",
    disk: "GDSA.rangeskill.disk",
    slingshot: "GDSA.rangeskill.slingshot",
    throwingaxe: "GDSA.rangeskill.throwingaxe",
    throwingknife: "GDSA.rangeskill.throwingknife",
    throwingspear: "GDSA.rangeskill.throwingspear"
}

GDSA.amourPlace = {
    none: "",
    head: "GDSA.armour.head",
    body: "GDSA.armour.body",
    back: "GDSA.armour.back",
    stomach: "GDSA.armour.stomach",
    rightarm: "GDSA.armour.rightarm",
    leftarm: "GDSA.armour.leftarm",
    rightleg: "GDSA.armour.rightleg",
    leftleg: "GDSA.armour.leftleg",
}

GDSA.ritualSkills = {
    none: "",
    gild: "GDSA.ritualSkills.gild",
    scha: "GDSA.ritualSkills.scha",
    alch: "GDSA.ritualSkills.alch",
    kris: "GDSA.ritualSkills.kris",
    hexe: "GDSA.ritualSkills.hexe",
    drui: "GDSA.ritualSkills.drui",
    geod: "GDSA.ritualSkills.geod",
    zibi: "GDSA.ritualSkills.zibi",
    durr: "GDSA.ritualSkills.durr",
    derw: "GDSA.ritualSkills.derw",
    tanz: "GDSA.ritualSkills.tanz",
    bard: "GDSA.ritualSkills.bard",
    gruf: "GDSA.ritualSkills.gruf",
    gban: "GDSA.ritualSkills.gban",
    gbin: "GDSA.ritualSkills.gbin",
    gauf: "GDSA.ritualSkills.gauf",
    petr: "GDSA.ritualSkills.petr"
}

GDSA.magicTraits = {
    none: "",
    anti: "GDSA.magicTraits.anti",
    conju: "GDSA.magicTraits.conju",
    attri: "GDSA.magicTraits.attri",
    sugge: "GDSA.magicTraits.sugge",
    form: "GDSA.magicTraits.form",
    ghost: "GDSA.magicTraits.ghost",
    heal: "GDSA.magicTraits.heal",
    forse: "GDSA.magicTraits.forse",
    summ: "GDSA.magicTraits.summ",
    reign: "GDSA.magicTraits.reign",
    illu: "GDSA.magicTraits.illu",
    force: "GDSA.magicTraits.force",
    limbus: "GDSA.magicTraits.limbus",
    meta: "GDSA.magicTraits.meta",
    object: "GDSA.magicTraits.object",
    damage: "GDSA.magicTraits.damage",
    teleke: "GDSA.magicTraits.teleke",
    tempo: "GDSA.magicTraits.tempo",
    soround: "GDSA.magicTraits.soround",
    speak: "GDSA.magicTraits.speak",
    daemo: "GDSA.magicTraits.daemo",
    blak: "GDSA.magicTraits.blak",
    belh: "GDSA.magicTraits.belh",
    char: "GDSA.magicTraits.char",
    loig: "GDSA.magicTraits.lolg",
    thar: "GDSA.magicTraits.thar",
    amaz: "GDSA.magicTraits.amaz",
    bels: "GDSA.magicTraits.bels",
    asfa: "GDSA.magicTraits.asfa",
    tasf: "GDSA.magicTraits.tasf",
    belz: "GDSA.magicTraits.belz",
    agri: "GDSA.magicTraits.agri",
    belk: "GDSA.magicTraits.belk",
    elem: "GDSA.magicTraits.elem",
    feur: "GDSA.magicTraits.feur",
    wass: "GDSA.magicTraits.wass",
    eis: "GDSA.magicTraits.eis",
    humu: "GDSA.magicTraits.humu",
    luft: "GDSA.magicTraits.luft",
    erz: "GDSA.magicTraits.erz"
}

GDSA.cuts = {
    none: "",
    brill: "GDSA.cuts.brill",
    rosen: "GDSA.cuts.rosen",
    pende: "GDSA.cuts.pende",
    caboc: "GDSA.cuts.caboc",
    tafel: "GDSA.cuts.tafel",
    smara: "GDSA.cuts.smara"
}

GDSA.wonderRange = {
    none: "",
    self: "GDSA.wonder.self",
    touc: "GDSA.wonder.touc",
    sigt: "GDSA.wonder.sigt",
    faar: "GDSA.wonder.faar"
}

GDSA.wonderCastDuration = {
    none: "",
    action: "GDSA.wonder.action",
    rounds: "GDSA.wonder.rounds",
    halfho: "GDSA.wonder.halfho",
    hours: "GDSA.wonder.hours",
    days: "GDSA.wonder.days"
}

GDSA.wonderTarget = [
    "",
    "G",
    "P",
    "PP",
    "PPP",
    "PPPP",
    "PPPPP",
    "Z",
    "ZZ",
    "ZZZ",
    "ZZZZ",
    "ZZZZZ"
]

GDSA.wonderPower = [
    "",
    "LkP*/2",
    "LkP*/2 + 5",
    "LkP*",
    "LkP* + 5",
    "LkP* + 10",
    "LkP* + 15",
    "LkP* + 20",
    "LkP* + 25",
    "LkP* + 30",
]

GDSA.wonderDuration = [
    "",
    "Augenblicklich",
    "LkP* KR",
    "LkP* x 10 KR",
    "LkP* SR",
    "LkP* Stunden",
    "LkP* Tage",
    "LkP* Wochen",
    "LkP* Monate",
    "LkP* Jahre",
    "Permanent",
    "Speziell"
]

GDSA.magicReps = {
    none: "",
    mag: "GDSA.reps.mag",
    dru: "GDSA.reps.dru",
    bor: "GDSA.reps.bor",
    srl: "GDSA.reps.srl",
    hex: "GDSA.reps.hex",
    elf: "GDSA.reps.elf",
    geo: "GDSA.reps.geo",
    ach: "GDSA.reps.ach",
    sch: "GDSA.reps.sch"
}

GDSA.holyReps = {
    none: "",
    pra: "GDSA.holyreps.pra",
    ron: "GDSA.holyreps.ron",
    phx: "GDSA.holyreps.phx",
    fir: "GDSA.holyreps.fir",
    tra: "GDSA.holyreps.tra",
    ing: "GDSA.holyreps.ing",
    bor: "GDSA.holyreps.bor",
    eff: "GDSA.holyreps.eff",
    hes: "GDSA.holyreps.hes",
    per: "GDSA.holyreps.per",
    rah: "GDSA.holyreps.rah",
    tsa: "GDSA.holyreps.tsa",
    ifi: "GDSA.holyreps.ifi",
    ave: "GDSA.holyreps.ave",
    kor: "GDSA.holyreps.kor",
    nan: "GDSA.holyreps.nan",
    swf: "GDSA.holyreps.swf",
    ang: "GDSA.holyreps.ang",
    tai: "GDSA.holyreps.tai",
    grv: "GDSA.holyreps.grv",
    him: "GDSA.holyreps.him",
    zsa: "GDSA.holyreps.zsa",
    hsz: "GDSA.holyreps.hsz",
    kam: "GDSA.holyreps.kam",
    nam: "GDSA.holyreps.nam"
}

GDSA.tempTypes = {
    none: "",
    adva: "GDSA.templates.adva",
    flaw: "GDSA.templates.flaw",
    trai: "GDSA.templates.sf",
    tale: "GDSA.templates.tal",
    kult: "GDSA.templates.kult"
}

GDSA.sfTypes = {
    none: "",
    general: "GDSA.templates.sfGeneral",
    combat: "GDSA.templates.sfCombat",
    magic: "GDSA.templates.sfMagic",
    object: "GDSA.templates.sfObject",
    rit: "GDSA.templates.sfRit",
    holy: "GDSA.templates.sfHoly"
}

GDSA.taleTypes = {
    none: "",
    combat: "GDSA.charactersheet.combatSkills",
    body: "GDSA.charactersheet.bodySkills",
    social: "GDSA.charactersheet.socialSkills",
    nature: "GDSA.charactersheet.natureSkills",
    knowledge: "GDSA.charactersheet.knowledgeSkills",
    lang: "GDSA.charactersheet.langSkills",
    sign: "GDSA.charactersheet.signSkills",
    craft: "GDSA.charactersheet.craftSkils",
    gift: "GDSA.charactersheet.giftSkills",
    meta: "GDSA.charactersheet.metaSkills"
}

GDSA.cultTypes = {
    twelf: "GDSA.charactersheet.twelf",
    half: "GDSA.charactersheet.half",
    other: "GDSA.charactersheet.other",
}

GDSA.taleAttributes = {
    none: "",
    mu: "GDSA.charactersheet.sMU",
    kl: "GDSA.charactersheet.sKL",
    in: "GDSA.charactersheet.sIN",
    ch: "GDSA.charactersheet.sCH",
    ff: "GDSA.charactersheet.sFF",
    ge: "GDSA.charactersheet.sGE",
    ko: "GDSA.charactersheet.sKO",
    kk: "GDSA.charactersheet.sKK"
}

GDSA.advantages = [
    "Begabung für [Ritual]",
    "Begabung für [Talent]",
    "Begabung für [Zauber]",
    "Begabung für [Merkmal]",

    "Göttergeschenk: Delfin",
    "Göttergeschenk: Eidechse",
    "Göttergeschenk: Firunsbär",
    "Göttergeschenk: Fuchs",
    "Göttergeschenk: Gans",
    "Göttergeschenk: Greif",
    "Göttergeschenk: Hammer/Amboss",
    "Göttergeschenk: Rabe",
    "Göttergeschenk: Schlange",
    "Göttergeschenk: Schwert",
    "Göttergeschenk: Sternenleere",
    "Göttergeschenk: Storch",
    "Göttergeschenk: Stute",

    "Guter Ruf",
    "Gutes Gedächtnis",
    "Halbzauberer",
    "Herausragende Balance",
    "Herausragende Eigenschaft: Mut",
    "Herausragende Eigenschaft: Klugheit",
    "Herausragende Eigenschaft: Intutition",
    "Herausragende Eigenschaft: Charisma",
    "Herausragende Eigenschaft: Fingerfertigkeit",
    "Herausragende Eigenschaft: Gewandtheit",
    "Herausragende Eigenschaft: Konstitution",
    "Herausragende Eigenschaft: Körperkraft",
    "Herausragender Sechster Sinn",
    "Herausragender Sinn",
    "Herausragendes Aussehen",
    "Heilsames Schnurren",
    "Hitzeresistenz",
    "Hohe Lebenskraft",
    "Hohe Magieresistenz",
    "Immunität gegen Gift",
    "Immunität gegen Krankheiten",
    "Innerer Kompass",
    "Kälteresistenz",
    "Kampfrausch",
    "Koboldfreund",
    "Kräfteschub",
    "Linkshänder",
    "Lizensierter Zauberer",
    "Machtvoller Vertrauter",
    "Magiedilletant",
    "Magiegespür",
    "Meisterhandwerk",
    "Nachtsicht",
    "Natürliche Waffen",
    "Natürlicher Rüstungsschutz",
    "Niedrige Schlechte Eigenschaft",
    "Paktgeschenk: Alterslosigkeit",
    "Paktgeschenk: Dämonische Hilfe",
    "Paktgeschenk: Dämonischer Fokus",
    "Paktgeschenk: Dämonische Waffe",
    "Paktgeschenk: Giftdrüsen",
    "Paktgeschenk: Lamijah",
    "Paktgeschenk: Neue Körperteile",
    "Paktgeschenk: Neun Leben",
    "Paktgeschenk: Pech wünschen",
    "Paktgeschenk: Schlafresistenz",
    "Paktgeschenk: Schmusekätzchen",
    "Paktgeschenk: Schutz vor göttlichem Wirken I",
    "Paktgeschenk: Schutz vor göttlichem Wirken II",
    "Paktgeschenk: Schutz vor göttlichem Wirken III",
    "Paktgeschenk: Schutz vor göttlichem Wirken IV",
    "Paktgeschenk: Schutz vor göttlichem Wirken V",
    "Paktgeschenk: Schutz vor göttlichem Wirken VI",
    "Paktgeschenk: Schutz vor göttlichem Wirken VII",
    "Paktgeschenk: Seelenschwert",
    "Paktgeschenk: Unverletzlichkeit",
    "Paktgeschenk: Zholvars Warnung",
    "Prophezeien",
    "Resistenz gegen Gift",
    "Resistenz gegen Krankheiten",
    "Richtungssinn",
    "Schlangenmensch",
    "Schnelle Heilung",
    "Schutzgeist",
    "Schwarze Gabe: Alpträume erzeugen",
    "Schwarze Gabe: Befehl der Lamijah",
    "Schwarze Gabe: Begehren überkomme euch!",
    "Schwarze Gabe: Belkelels Ekstase",
    "Schwarze Gabe: Beutesinn",
    "Schwarze Gabe: Brünstigkeit erzeugen",
    "Schwarze Gabe: Chimärenerschaffung",
    "Schwarze Gabe: Fischgift",
    "Schwarze Gabe: Geschwindigkeit",
    "Schwarze Gabe: Gier erzeugen",
    "Schwarze Gabe: Goldene Hand",
    "Schwarze Gabe: Hauch der Pestilenz",
    "Schwarze Gabe: Herrschaft über Dschinne",
    "Schwarze Gabe: Herrschaft über Geister",
    "Schwarze Gabe: Katzenruf",
    "Schwarze Gabe: Kornfäule",
    "Schwarze Gabe: Krakenruf",
    "Schwarze Gabe: Lähmende Furcht",
    "Schwarze Gabe: Leichengespür",
    "Schwarze Gabe: Lodernder Blick",
    "Schwarze Gabe: Macht des Wahnsinns",
    "Schwarze Gabe: Magnum Opus des Erzdämons",
    "Schwarze Gabe: Meister der Form",
    "Schwarze Gabe: Nagrachs Hauch",
    "Schwarze Gabe: Orkanbö",
    "Schwarze Gabe: Raub der Lebenskraft",
    "Schwarze Gabe: Schleichen in den Schatten",
    "Schwarze Gabe: Spur des Missetäters",
    "Schwarze Gabe: Todeshauch",
    "Schwarze Gabe: Trugwelten erschaffen",
    "Schwarze Gabe: Verborgenes Wissen erspüren",
    "Schwarze Gabe: Wahrheitssinn",
    "Schwarze Gabe: Wundschmerz",
    "Schwarze Gabe: Zwist und Hader",
    "Schwer zu verzaubern",
    "Soziale Anpassungsfähigkeit",
    "Sprachgefühl",
    "Talentschub",
    "Tierempathie",
    "Tierempathie (speziell)",
    "Tierfreund",
    "Titularadel",
    "Übernatürliche Begabung",
    "Unbeschwertes Zaubern",
    "Verbindungen",
    "Verhüllte Aura",
    "Veteran",
    "Viertelzauberer",
    "Vollzauberer",
    "Vom Schicksal begünstigt",
    "Wesen der Nacht",
    "Wohlklang",
    "Wolfskind",
    "Zäher Hund",
    "Zauberhaar",
    "Zeitgefühl",
    "Zusätzliche Gliedmassen",
    "Zweistimmiger Gesang",
    "Zwergennase",
    "Herausragende Eigenschaft",
    "Dschinngeboren (ohne VZ)",
    "Dschinngeboren (mit VZ)"
];

GDSA.disadvantages = [
    "Aberglaube",
    "Agrimothwahn",
    "Albino",
    "Angst vor (häufiger Auslöser)",
    "Angst vor (seltener Auslöser)",
    "Angst vor Feuer",
    "Angst vor Insekten",
    "Angst vor Menschenmassen",
    "Angst vor Nagetieren",
    "Angst vor Pelztieren",
    "Angst vor Reptilien",
    "Angst vor Spinnen",
    "Angst vor Wasser",
    "Animalische Magie",
    "Arkanophobie",
    "Arroganz",
    "Artefaktgebunden",
    "Astraler Block",
    "Astraler Block",
    "Autoritätsgläubig",
    "Behäbig",
    "Blutdurst",
    "Blutrausch",
    "Brünstigkeit",
    "Charyptophilie",
    "Dunkelangst",
    "Einarmig",
    "Einäugig",
    "Einbeinig",
    "Einbildungen",
    "Eingeschränkter Sinn",
    "Eingeschränkte Elementarnähe",
    "Einhändig",
    "Eitelkeit",
    "Elfische Weltsicht",
    "Farbenblind",
    "Feind",
    "Feste Gewohnheit",
    "Festgefügtes Denken",
    "Fettleibig",
    "Fluch der Finsternis",
    "Geiz",
    "Gerechtigkeitswahn",
    "Gesucht",
    "Glasknochen",
    "Goldgier",
    "Grausamkeit",
    "Grössenwahn",
    "Heimwehkrank",
    "Herrschsucht",
    "Hitzeempfindlichkeit",
    "Höhenangst",
    "Impulsiv",
    "Jagdfieber",
    "Jähzorn",
    "Kälteempfindlichkeit",
    "Kältestarre",
    "Kein Vertrauter",
    "Kleinwüchsig",
    "Konstruktionswahn",
    "Körpergebundene Kraft",
    "Krankhafte Nekromantie",
    "Krankhafte Reinlichkeit",
    "Krankheitsanfällig",
    "Kristallgebunden",
    "Kurzatmig",
    "Lahm",
    "Landangst",
    "Lästige Mindergeister",
    "Lichtempfindlich",
    "Lichtscheu",
    "Madas Fluch",
    "Madas Fluch (stark)",
    "Medium",
    "Meeresangst",
    "Miserable Eigenschaft",
    "Mondsüchtig",
    "Moralkodex",
    "Moralkodex [Angrosch-Kult]",
    "Moralkodex [Aves-Kirche]",
    "Moralkodex [Badilakaner]",
    "Moralkodex [Boron-Kirche]",
    "Moralkodex [Bund des wahren Glaubens]",
    "Moralkodex [DDZ]",
    "Moralkodex [Dreischwesternorden]",
    "Moralkodex [Efferd-Kirche]",
    "Moralkodex [Firun-Kirche]",
    "Moralkodex [Hesinde-Kirche]",
    "Moralkodex [Heshinja]",
    "Moralkodex [H'Szint-Kult]",
    "Moralkodex [Ifirn-Kirche]",
    "Moralkodex [Ingerimm-Kirche]",
    "Moralkodex [Kor-Kirche]",
    "Moralkodex [Nandus-Kirche]",
    "Moralkodex [Peraine-Kirche]",
    "Moralkodex [Phex-Kirche]",
    "Moralkodex [Praios-Kirche]",
    "Moralkodex [Rahja-Kirche]",
    "Moralkodex [Rondra-Kirche]",
    "Moralkodex [Swafnir-Kult]",
    "Moralkodex [Therbûniten]",
    "Moralkodex [Travia-Kirche]",
    "Moralkodex [Tsa-Kirche]",
    "Moralkodex [Zsaah-Kult]",
    "Morbidität",
    "Nachtblind",
    "Nagrachwahn",
    "Nahrungsrestriktion",
    "Neid",
    "Neugier",
    "Niedrige Astralkraft",
    "Niedrige Lebenskraft",
    "Niedrige Magieresistenz",
    "Paktierer",
    "Pechmagnet",
    "Platzangst",
    "Prinzipientreue",
    "Rachsucht",
    "Randgruppe",
    "Raubtiergeruch",
    "Raumangst",
    "Rückschlag",
    "Ruhelosigkeit",
    "Schlaflosigkeit",
    "Schlafstörungen",
    "Schlafwandler",
    "Schlechte Regeneration",
    "Schlechter Ruf",
    "Schneller alternd",
    "Schöpferwahn",
    "Schulden",
    "Schwache Ausstrahlung",
    "Schwacher Astralkörper",
    "Schwanzlos",
    "Seffer Manich",
    "Selbstgespräche",
    "Sensibler Geruchssinn",
    "Sippenlosigkeit",
    "Sonnensucht",
    "Speisegebote",
    "Spielsucht",
    "Sprachfehler",
    "Spruchhemmung",
    "Stigma",
    "Streitsucht",
    "Stubenhocker",
    "Sucht",
    "Thesisgebunden",
    "Tollpatsch",
    "Totenangst",
    "Trägheit",
    "Treuelosigkeit",
    "Übler Geruch",
    "Unangenehme Stimme",
    "Unansehnlich",
    "Unbewusster Viertelzauberer",
    "Unfähigkeit für [Merkmal]",
    "Unfähigkeit für [Talent]",
    "Unfähigkeit für [Talentgruppe]",
    "Unfrei",
    "Ungebildet",
    "Unstet",
    "Unverträglichkeit mit verarbeitetem Metall",
    "Vergesslichkeit",
    "Verpflichtungen",
    "Verschwendungssucht",
    "Verwöhnt",
    "Vorurteile gegen",
    "Vorurteile gegen (stark)",
    "Wahnvorstellungen",
    "Wahrer Name",
    "Weltfremd bzgl.",
    "Widerwärtiges Aussehen",
    "Wilde Magie",
    "Zielschwierigkeiten",
    "Zögerlicher Zauberer",
    "Zwergenwuchs",
    "Eingeschränkter Sinn",
    "Miserable Eigenschaft",
    "Schulden",
    "Sucht",
    "Unfähigkeit für [Merkmal]",
    "Unfähigkeit für [Talent]",
    "Unfähigkeit für [Talentgruppe]",
    "Schlechte Eigenschaft",
    "Größenwahn"
];

GDSA.sfgeneral = [
    "Ortskenntnis", 
    "Talentspezialisierung",
    "Berufsgeheimnis",
    "Zauberspezialisierung",
    "Wahrer Name:",
    "Die Gestalt aus Rauch"
];

GDSA.sfobject = [
    "Apport",
    "Bannschwert",
    "Schalenzauber",
    "Kugelzauber",
    "Stabzauber",
    "Keulenritual",
    "Druidisches Dolchritual",
    "Schlangenring-Zauber",
    "Gabe des Odûn",
    "Schuppenbeutel",
    "Kristallpendel",
    "Szepter",
    "Tapasuul",
    "Schlangenszepters"
];

GDSA.sfrit = [
    "Elfenlied",
    "Druidisches Herrschaftsritual",
    "Hexenritual",
    "Ritual",
    "Hexenfluch"
];